language: cpp

compiler:
  - gcc
  - clang

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - clang

script:
  - cd test && mkdir build && cd build && cmake .. && make

sudo: false