dist: trusty
sudo: false
language: cpp

matrix:
  include:
    
    - os: linux
      env: TEST_RUN=TRUE BENCH_RUN=FALSE
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    
    - os: linux
      env: TEST_RUN=TRUE BENCH_RUN=FALSE
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    
    - os: linux
      env: TEST_RUN=TRUE BENCH_RUN=FALSE
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    - os: linux
      env: TEST_RUN=TRUE BENCH_RUN=FALSE
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - chmod +x scripts/test.sh
    - chmod +x scripts/bench.sh
    - eval "${MATRIX_EVAL}"

script:
  - scripts/test.sh
  - scripts/bench.sh
